//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 01:42:38 PM ICT 
//


package project.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.canvas.vyvtt package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Painting_QNAME = new QName("http://canvas.com/vyvtt", "painting");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.canvas.vyvtt
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Painting }
     * 
     */
    public Painting createPainting() {
        return new Painting();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Canvas }
     * 
     */
    public Canvas createCanvas() {
        return new Canvas();
    }

    /**
     * Create an instance of {@link Detail }
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Painting }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://canvas.com/vyvtt", name = "painting")
    public JAXBElement<Painting> createPainting(Painting value) {
        return new JAXBElement<Painting>(_Painting_QNAME, Painting.class, null, value);
    }

}
