//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 01:42:38 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://canvas.com/vyvtt", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package project.jaxb;
